export const PENALTY_POINTS = {
  LATE: 2,
  MEAL_RETURN_DELAY: 2,
  OUTING_RETURN_DELAY: 2,
  DROWSINESS: 2,
  POOR_ATTITUDE: 2,
  EATING_IN_STUDY_ROOM: 2,
  SEAT_AWAY: 2,
  DISTURBANCE: 2,
  POOR_CLEANUP: 2,

  UNAUTHORIZED_LATE: 5,
  ELECTRONIC_DEVICE_USE: 5,
  UNAUTHORIZED_MOVEMENT: 5,
  UNAUTHORIZED_POWER_NAP: 5,
  SMOKING_IN_BUILDING: 5,

  UNAUTHORIZED_ABSENCE: 10,
  UNAUTHORIZED_EARLY_LEAVE: 10,
  IGNORING_ADMIN_INSTRUCTION: 10,
  UNAUTHORIZED_ITEM_USE: 10,
} as const;

export type PenaltyReasonCode = keyof typeof PENALTY_POINTS;

export const PENALTY_REASON_LABEL: Record<PenaltyReasonCode, string> = {
  LATE: '지각',
  MEAL_RETURN_DELAY: '식사 복귀 지연',
  OUTING_RETURN_DELAY: '외출 복귀 지연',
  DROWSINESS: '졸음',
  POOR_ATTITUDE: '학습태도 불량',
  EATING_IN_STUDY_ROOM: '학습실 취식',
  SEAT_AWAY: '자리이탈',
  DISTURBANCE: '소란',
  POOR_CLEANUP: '정리 불량',
  UNAUTHORIZED_LATE: '무단지각',
  ELECTRONIC_DEVICE_USE: '전자기기 사용',
  UNAUTHORIZED_MOVEMENT: '무단이동',
  UNAUTHORIZED_POWER_NAP: '무단 파워냅 이용',
  SMOKING_IN_BUILDING: '건물 내 흡연',
  UNAUTHORIZED_ABSENCE: '무단결석',
  UNAUTHORIZED_EARLY_LEAVE: '무단조퇴',
  IGNORING_ADMIN_INSTRUCTION: '관리자 지시 불이행',
  UNAUTHORIZED_ITEM_USE: '타인 물건 무단 사용',
};

export const WARNING_THRESHOLDS = {
  FIRST_WARNING: 10,
  SECOND_WARNING: 20,
  EXPULSION: 30,
} as const;

export const POWER_NAP_MAX_MINUTES = 40;
export const POWER_NAP_DAILY_LIMIT = 1;
