import { supabase } from '@/lib/supabase/client';

export interface WarningRecordWithStudent {
  id: string;
  studentId: string;
  studentName: string;
  warningLevel: number;
  triggeredPenaltyTotal: number;
  isAutoGenerated: boolean;
  note: string | null;
  issuedAt: string;
}

interface WarningJoinRow {
  id: string;
  student_id: string;
  warning_level: number;
  triggered_penalty_total: number;
  is_auto_generated: boolean;
  note: string | null;
  issued_at: string;
  student_profiles: { users: { name: string } | null } | null;
}

export async function fetchAllWarningRecords(limit = 50): Promise<WarningRecordWithStudent[]> {
  const { data, error } = await supabase
    .from('warning_records')
    .select(
      'id, student_id, warning_level, triggered_penalty_total, is_auto_generated, note, issued_at, student_profiles(users(name))'
    )
    .order('issued_at', { ascending: false })
    .limit(limit);

  if (error) throw error;

  return (data as unknown as WarningJoinRow[]).map((row) => ({
    id: row.id,
    studentId: row.student_id,
    studentName: row.student_profiles?.users?.name ?? '(알 수 없음)',
    warningLevel: row.warning_level,
    triggeredPenaltyTotal: row.triggered_penalty_total,
    isAutoGenerated: row.is_auto_generated,
    note: row.note,
    issuedAt: row.issued_at,
  }));
}

export async function manualExpelStudent(params: {
  studentId: string;
  issuedBy: string;
  note: string;
}): Promise<void> {
  const { data: profile, error: profileError } = await supabase
    .from('student_profiles')
    .select('current_penalty_points')
    .eq('id', params.studentId)
    .single();
  if (profileError) throw profileError;

  const { error: warningError } = await supabase.from('warning_records').insert({
    student_id: params.studentId,
    warning_level: 3,
    triggered_penalty_total: profile.current_penalty_points,
    is_auto_generated: false,
    issued_by: params.issuedBy,
    note: params.note,
  });
  if (warningError) throw warningError;

  const { error: updateError } = await supabase
    .from('student_profiles')
    .update({ membership_status: 'expelled', warning_count: 3 })
    .eq('id', params.studentId);
  if (updateError) throw updateError;
}
