import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useStudentsQuery } from '@/features/admin-students/hooks';
import { useManualExpelMutation, useWarningRecordsFeedQuery } from '@/features/admin-warning/hooks';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { FormField } from '@/components/ui/FormField';
import { EmptyState } from '@/components/ui/EmptyState';

export default function WarningsPage() {
  const { user } = useAuth();
  const { data: students } = useStudentsQuery();
  const { data: records } = useWarningRecordsFeedQuery();
  const expelMutation = useManualExpelMutation();

  const [studentId, setStudentId] = useState('');
  const [note, setNote] = useState('');

  const handleExpel = async () => {
    if (!studentId || !note.trim()) return;
    if (!window.confirm('선택한 학생을 퇴원 처리하시겠습니까?')) return;
    await expelMutation.mutateAsync({ studentId, issuedBy: user!.id, note });
    setStudentId('');
    setNote('');
  };

  return (
    <div className="flex flex-col gap-6">
      <h2 className="text-lg font-semibold text-gray-900">경고 관리</h2>
      <p className="text-sm text-gray-500">
        1차/2차 경고와 퇴원은 벌점 누적에 따라 자동으로 발생합니다. 아래에서는 자동 규칙과 무관하게
        수동으로 퇴원 처리를 할 수 있습니다.
      </p>

      <Card>
        <p className="mb-3 text-sm font-semibold text-gray-700">수동 퇴원 처리</p>
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
          <FormField label="학생" htmlFor="expel-student">
            <select
              id="expel-student"
              value={studentId}
              onChange={(event) => setStudentId(event.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
            >
              <option value="">학생 선택</option>
              {(students ?? []).map((student) => (
                <option key={student.id} value={student.id}>
                  {student.name} ({student.phone})
                </option>
              ))}
            </select>
          </FormField>
          <FormField label="처리 사유" htmlFor="expel-note">
            <input
              id="expel-note"
              value={note}
              onChange={(event) => setNote(event.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
            />
          </FormField>
        </div>
        <Button
          variant="danger"
          className="mt-3"
          disabled={!studentId || !note.trim() || expelMutation.isPending}
          onClick={handleExpel}
        >
          퇴원 처리
        </Button>
      </Card>

      <div>
        <h3 className="mb-2 text-sm font-semibold text-gray-700">경고/퇴원 이력</h3>
        {!records || records.length === 0 ? (
          <EmptyState title="경고 이력이 없습니다" />
        ) : (
          <ul className="flex flex-col gap-2">
            {records.map((record) => (
              <li
                key={record.id}
                className="flex items-center justify-between rounded-md border border-gray-200 bg-white px-3 py-2 text-sm"
              >
                <div>
                  <p className="font-medium text-gray-900">{record.studentName}</p>
                  <p className="text-xs text-gray-500">
                    {new Date(record.issuedAt).toLocaleString('ko-KR')} · 누적 {record.triggeredPenaltyTotal}점
                    {!record.isAutoGenerated && ' · 수동 처리'}
                    {record.note && ` · ${record.note}`}
                  </p>
                </div>
                <Badge tone="danger">{record.warningLevel === 3 ? '퇴원' : `${record.warningLevel}차 경고`}</Badge>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
